---
title: "test_fe_automation"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{simple_example}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

https://stackoverflow.com/questions/49816669/how-to-use-map-from-purrr-with-dplyrmutate-to-create-multiple-new-columns-base

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
order_markers <- c("CD3", "CD4", "CD8",  "CD44", "CD103", "Sca1", "IL_17","CTLA4",
                      "CD27",  "CD153", "KLRG1", "IFN",  "CD122", "PD1", "CD62L",
                      "IL_10", "CD28","TNF")

inputss %>%
  mutate(order_markers = map_dfr(list(order_markers), fe(add_quantile, .x, .x)))


fe_automate <- function(x) {
  transmute(df, !! paste0("fe_", quo_name(x)) := pmap_dbl(select(df, start_with(x)), fe(add_quantile, x)))
}

map_dfc(order_markers, fe_automate)

letters[1:3]

  mutate(CD3 = fe(add_quantile, CD3, "CD3"),
         CD4 = fe(add_quantile, CD4, "CD4"),
         CD8 = fe(add_quantile, CD8, "CD8"),
         CD44 = fe(add_quantile, CD44, "CD44"),
         CD103 = fe(add_quantile, CD103, "CD103"),
         Sca1 = fe(add_quantile, Sca1, "Sca1"),
         IL_17 = fe(add_quantile, IL_17, "IL_17"),
         CD69 = fe(add_quantile, CD69, "CD69"),
         CTLA4 = fe(add_quantile, CTLA4, "CTLA4"),
         CD27 = fe(add_quantile, CD27, "CD27"),
         CD153 = fe(add_quantile, CD153, "CD153"),
         KLRG1 = fe(add_quantile, KLRG1, "KLRG1"),
         IFN = fe(add_quantile, IFN, "IFN"),
         FoxP3 = fe(add_quantile, FoxP3, "FoxP3"),
         CD122 = fe(add_quantile, CD122, "CD122"),
         PD1 = fe(add_quantile, PD1, "PD1"),
         CD62L = fe(add_quantile, CD62L, "CD62L"),
         IL_10 = fe(add_quantile, IL_10, "IL_10"),
         CD28 = fe(add_quantile, CD28, "CD28"),
         TNF = fe(add_quantile, TNF, "TNF")) %>%
  select(-`Zombie Nir-A`, -`AF-A`, -`SSC-A`, -FoxP3, -CD69) %>%
  count_calc()
```

